version: '3.3'
services:
  dp-dataset-api:
    build:
      context: ../../../dp-dataset-api
      dockerfile: Dockerfile.local
    command:
      - go
      - test
      - -cover
      - -race
      - -coverpkg=github.com/ONSdigital/dp-dataset-api/...
      - -component
    volumes:
      - ../../:/dp-dataset-api
    depends_on:
      - kafka-1
    ports:
      - 26300:26300
    environment:
      BIND_ADDR: ":22000"
      KAFKA_ADDR: "kafka-1:9092"
      SERVICE_AUTH_TOKEN: "testToken"
      COMPONENT_TEST_USE_LOG_FILE: "${COMPONENT_TEST_USE_LOG_FILE-false}"
      KAFKA_SEC_PROTO: ""
