version: "2"
run:
  concurrency: 4
  timeout: 10m
linters:
  default: none
  enable:
    - dogsled
    - errcheck
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 100
    gocognit:
      min-complexity: 40
    goconst:
      min-len: 2
      min-occurrences: 4
    gocritic:
      disabled-checks:
        - wrapperFunc
        - dupImport
        - ifElseChain
        - octalLiteral
        - hugeParam
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 140
    misspell:
      locale: UK
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: unused-parameter
      - linters:
          - revive
        path: _test.go
        text: dot-imports
        source: github.com/smartystreets/goconvey/convey
      - linters:
          - goconst
        path: api/static_versions_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
